### ISSUE TITLE
Correct CSSA/sgx_exit handling

### ISSUE THREAD

**Issue by patrickb314** [patrickb314/janusSGX#8]
The current emulator starts with a CSSA of 2, not 0, which is not architecturally correct. Just changing the default CSSA to 0 in the user code breaks signing of enclaves currently, probably because of a related change that is needed in the emulator.

**Comment by johnmwshih** [comment]
We've already fixed this issue in current version OpenSGX. It's due to we wrongly put stack region and SSA region together. Now during enclave initialization, we allocate memory for SSA and stack separately.

**Comment by patrickb314** [comment]
How do you handle stack allocation? You still need a separate stack for each entry into the TCS, which is why I kept it in the SSA and just made the SSA region bigger. Otherwise, you have to worry about an EENTER->AEX->EENTER->EEXIT->ERESUME sequence, where the second EENTER corrupts the stack of the first, right?
